/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author eve
 */

import java.awt.Image;
import javax.swing.ImageIcon;
import java.net.URL;

public class AutegestionEstudiantil extends javax.swing.JFrame {
    
    //Llamar los paneles a la pantalla principal
    
    PanelInicio pantallaInicio = new PanelInicio();
    PanelPerfil pantallaPerfil = new PanelPerfil();
    PanelMaterias pantallaMaterias = new PanelMaterias();
    PanelReportes pantallaReportes = new PanelReportes();
    
    
    
   
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AutegestionEstudiantil.class.getName());

    /**
     * Creates new form AutegestionEstudiantil
     */
    public AutegestionEstudiantil() {
        
        //Promt: Como colocar imagenes en java swing
        initComponents();
        colocarIcono(lblIconoPerfil, "/imgs/usuario.png");
        colocarIcono(lblIconoInicio, "/imgs/NInicio.png");
        colocarIcono(lblIconoMaterias, "/imgs/NMaterias.png");
        colocarIcono(lblIconoReportes, "/imgs/NReportes.png");
        
        aplicarEfectoHover(jPanelPerfil, btnPerfil);   // Perfil
        aplicarEfectoHover(jPanelInicio, btnInicio);   // Inicio
        aplicarEfectoHover(jPanelMaterias, btnMaterias); // Materias
        aplicarEfectoHover(jPanelReportes, btnReportes); // Reportes
        
        PanelContenedor.add(pantallaInicio, "Pantalla_Inicio");
        PanelContenedor.add(pantallaPerfil, "Pantalla_Perfil");
        PanelContenedor.add(pantallaMaterias, "Pantalla_Materias");
        PanelContenedor.add(pantallaReportes, "Pantalla_Reportes");
        
        java.awt.CardLayout layout = (java.awt.CardLayout) PanelContenedor.getLayout();
        layout.show(PanelContenedor, "Pantalla_Inicio");
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelNavegacion = new javax.swing.JPanel();
        jPanelPerfil = new javax.swing.JPanel();
        lblIconoPerfil = new javax.swing.JLabel();
        btnPerfil = new javax.swing.JButton();
        jPanelInicio = new javax.swing.JPanel();
        lblIconoInicio = new javax.swing.JLabel();
        btnInicio = new javax.swing.JButton();
        jPanelMaterias = new javax.swing.JPanel();
        btnMaterias = new javax.swing.JButton();
        lblIconoMaterias = new javax.swing.JLabel();
        jPanelReportes = new javax.swing.JPanel();
        btnReportes = new javax.swing.JButton();
        lblIconoReportes = new javax.swing.JLabel();
        PanelContenedor = new javax.swing.JPanel();
        Menu = new javax.swing.JMenuBar();
        mInicio = new javax.swing.JMenu();
        mArchivo = new javax.swing.JMenu();
        mReportes = new javax.swing.JMenu();
        mAyuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Main"); // NOI18N
        setPreferredSize(new java.awt.Dimension(850, 600));
        setResizable(false);

        PanelNavegacion.setBackground(new java.awt.Color(10, 20, 80));
        PanelNavegacion.setName("PanelNavegacion"); // NOI18N
        PanelNavegacion.setPreferredSize(new java.awt.Dimension(146, 609));

        jPanelPerfil.setBackground(new java.awt.Color(10, 20, 80));

        btnPerfil.setBackground(new java.awt.Color(255, 255, 255));
        btnPerfil.setForeground(new java.awt.Color(255, 255, 255));
        btnPerfil.setText("Perfil");
        btnPerfil.setBorderPainted(false);
        btnPerfil.setContentAreaFilled(false);
        btnPerfil.addActionListener(this::btnPerfilActionPerformed);

        javax.swing.GroupLayout jPanelPerfilLayout = new javax.swing.GroupLayout(jPanelPerfil);
        jPanelPerfil.setLayout(jPanelPerfilLayout);
        jPanelPerfilLayout.setHorizontalGroup(
            jPanelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPerfilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIconoPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPerfil)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPerfilLayout.setVerticalGroup(
            jPanelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPerfilLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(lblIconoPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(jPanelPerfilLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(btnPerfil)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelInicio.setBackground(new java.awt.Color(10, 20, 80));

        btnInicio.setBackground(new java.awt.Color(255, 255, 255));
        btnInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnInicio.setText("Inicio");
        btnInicio.setBorderPainted(false);
        btnInicio.setContentAreaFilled(false);
        btnInicio.setFocusPainted(false);
        btnInicio.addActionListener(this::btnInicioActionPerformed);

        javax.swing.GroupLayout jPanelInicioLayout = new javax.swing.GroupLayout(jPanelInicio);
        jPanelInicio.setLayout(jPanelInicioLayout);
        jPanelInicioLayout.setHorizontalGroup(
            jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIconoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelInicioLayout.setVerticalGroup(
            jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInicioLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblIconoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInicio))
                .addGap(8, 8, 8))
        );

        jPanelMaterias.setBackground(new java.awt.Color(10, 20, 80));

        btnMaterias.setBackground(new java.awt.Color(255, 255, 255));
        btnMaterias.setForeground(new java.awt.Color(255, 255, 255));
        btnMaterias.setText("Materias");
        btnMaterias.setBorderPainted(false);
        btnMaterias.setContentAreaFilled(false);
        btnMaterias.setFocusPainted(false);
        btnMaterias.addActionListener(this::btnMateriasActionPerformed);

        javax.swing.GroupLayout jPanelMateriasLayout = new javax.swing.GroupLayout(jPanelMaterias);
        jPanelMaterias.setLayout(jPanelMateriasLayout);
        jPanelMateriasLayout.setHorizontalGroup(
            jPanelMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMateriasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIconoMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMaterias)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelMateriasLayout.setVerticalGroup(
            jPanelMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMateriasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblIconoMaterias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMaterias, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addGap(17, 17, 17))
        );

        jPanelReportes.setBackground(new java.awt.Color(10, 20, 80));

        btnReportes.setBackground(new java.awt.Color(255, 255, 255));
        btnReportes.setForeground(new java.awt.Color(255, 255, 255));
        btnReportes.setText("Reportes");
        btnReportes.setBorderPainted(false);
        btnReportes.setContentAreaFilled(false);
        btnReportes.setFocusPainted(false);
        btnReportes.addActionListener(this::btnReportesActionPerformed);

        javax.swing.GroupLayout jPanelReportesLayout = new javax.swing.GroupLayout(jPanelReportes);
        jPanelReportes.setLayout(jPanelReportesLayout);
        jPanelReportesLayout.setHorizontalGroup(
            jPanelReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelReportesLayout.createSequentialGroup()
                .addComponent(lblIconoReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReportes)
                .addContainerGap(638, Short.MAX_VALUE))
        );
        jPanelReportesLayout.setVerticalGroup(
            jPanelReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelReportesLayout.createSequentialGroup()
                .addGroup(jPanelReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblIconoReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReportes))
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout PanelNavegacionLayout = new javax.swing.GroupLayout(PanelNavegacion);
        PanelNavegacion.setLayout(PanelNavegacionLayout);
        PanelNavegacionLayout.setHorizontalGroup(
            PanelNavegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelMaterias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelNavegacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelReportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelNavegacionLayout.setVerticalGroup(
            PanelNavegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNavegacionLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jPanelPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelReportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(222, Short.MAX_VALUE))
        );

        getContentPane().add(PanelNavegacion, java.awt.BorderLayout.LINE_START);

        PanelContenedor.setBackground(new java.awt.Color(204, 204, 204));
        PanelContenedor.setPreferredSize(new java.awt.Dimension(850, 600));
        PanelContenedor.setLayout(new java.awt.CardLayout());
        getContentPane().add(PanelContenedor, java.awt.BorderLayout.CENTER);

        mInicio.setText("Inicio");
        Menu.add(mInicio);

        mArchivo.setText("Archivo");
        Menu.add(mArchivo);

        mReportes.setText("Reportes");
        Menu.add(mReportes);

        mAyuda.setText("Ayuda");
        Menu.add(mAyuda);

        setJMenuBar(Menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMateriasActionPerformed
        java.awt.CardLayout layout = (java.awt.CardLayout) PanelContenedor.getLayout();
         layout.show(PanelContenedor, "Pantalla_Materias");
    }//GEN-LAST:event_btnMateriasActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
         java.awt.CardLayout layout = (java.awt.CardLayout) PanelContenedor.getLayout();
         layout.show(PanelContenedor, "Pantalla_Inicio");
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed
        // TODO add your handling code here:
        java.awt.CardLayout layout = (java.awt.CardLayout) PanelContenedor.getLayout();
         layout.show(PanelContenedor, "Pantalla_Perfil");
    }//GEN-LAST:event_btnPerfilActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        // TODO add your handling code here:
        java.awt.CardLayout layout = (java.awt.CardLayout) PanelContenedor.getLayout();
         layout.show(PanelContenedor, "Pantalla_Reportes");
    }//GEN-LAST:event_btnReportesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AutegestionEstudiantil().setVisible(true));
        

        
        
    }
    
// Método para cargar y escalar tus imágenes sin errores de importación
    private void colocarIcono(javax.swing.JLabel labelDestino, String rutaIcono) {
        try {
            URL url = getClass().getResource(rutaIcono);
            if (url != null) {
                ImageIcon iconOriginal = new ImageIcon(url);
                
                // Salvavidas por si NetBeans lee el tamaño en 0 antes de renderizar
                int ancho = labelDestino.getWidth() > 0 ? labelDestino.getWidth() : 32;
                int alto = labelDestino.getHeight() > 0 ? labelDestino.getHeight() : 32;
                
                Image imgEscalada = iconOriginal.getImage().getScaledInstance(ancho, alto, Image.SCALE_SMOOTH);
                labelDestino.setIcon(new ImageIcon(imgEscalada));
            } else {
                System.err.println("No se encontró el icono en la ruta: " + rutaIcono);
            }
        } catch (Exception e) {
            System.err.println("Error al cargar la imagen: " + e.getMessage());
        }
    }
    
    //promt: como colocar hover en java jFrame
    private void aplicarEfectoHover(javax.swing.JPanel panel, javax.swing.JButton boton) {
        // 1. Tus colores base de Figma
        java.awt.Color azulFondoOriginal = new java.awt.Color(10, 20, 80); // El azul oscuro de base

        // 2. Un azul sutilmente más claro para el reflejo (Efecto sutil)
        java.awt.Color azulFondoHover = new java.awt.Color(24, 36, 105); 

        // 3. El texto se mantiene blanco o un blanco brillante
        java.awt.Color textoColorNormal = new java.awt.Color(220, 225, 235); // Blanco sutilmente grisáceo en reposo
        java.awt.Color textoColorHover = java.awt.Color.WHITE;               // Blanco puro brillante al pasar el mouse

        // Configuración inicial para que combine con el reposo
        boton.setForeground(textoColorNormal);

        boton.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel.setBackground(azulFondoHover);  // Se ilumina el fondo sutilmente
                boton.setForeground(textoColorHover);  // El texto brilla en blanco puro
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel.setBackground(azulFondoOriginal); // Vuelve al azul oscuro
                boton.setForeground(textoColorNormal);   // Vuelve al tono normal
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Menu;
    private javax.swing.JPanel PanelContenedor;
    private javax.swing.JPanel PanelNavegacion;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnMaterias;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JButton btnReportes;
    private javax.swing.JPanel jPanelInicio;
    private javax.swing.JPanel jPanelMaterias;
    private javax.swing.JPanel jPanelPerfil;
    private javax.swing.JPanel jPanelReportes;
    private javax.swing.JLabel lblIconoInicio;
    private javax.swing.JLabel lblIconoMaterias;
    private javax.swing.JLabel lblIconoPerfil;
    private javax.swing.JLabel lblIconoReportes;
    private javax.swing.JMenu mArchivo;
    private javax.swing.JMenu mAyuda;
    private javax.swing.JMenu mInicio;
    private javax.swing.JMenu mReportes;
    // End of variables declaration//GEN-END:variables
}
